---
title: "final-evaluation"
output: html_document
date: "2024-03-07"
---

# Assignment Info

- **Student name:** Kaiwen (Katia) 
- **Project title:** Gender-Biased Language in Maternal Directed Speech
- **Submission date:** Mar 4 at 2:33pm 

## Report plan summary

1. Specific Plans for Analysis, Table, and Figure Chunks
Analysis: I plan to utilize 2-way ANOVA to analyze the impact of gender and maternal language input on children’s language development. This statistical method is appropriate as it allows to examine the interaction effects between two independent variables (gender and types of maternal language input) on the dependent variables (count of overall utterances, adjectives, and nouns).
Table Chunks: My tables will detail the count of overall utterances, as well as those containing adjectives and nouns, differentiated by gender. This quantitative summary will provide a clear overview of the data, facilitating comparison between 2 gender groups.
Figure Chunks: I will employ histograms to visually compare the counts of overall utterances, adjectives, and nouns between gender groups. Additionally, a boxplot with jitter will illustrate the variations in frequency of maternal language input to different gender groups, effectively highlighting any disparities.

2. Distribution of the 1500+ Words Across Sections
Introduction (400+ words): This section will introduce the concept of gender socialization and the critical role of maternal language input in early child development. 
Methods (500+ words): I will detail the selection and analysis of data from six corpuses from CHILDES, emphasizing my process of data organization, cleaning, and preparation. I’ll explain the classification of children’s gender as the independent variable and maternal input of gender-biased adjectives and nouns as the dependent variables, alongside my analytical approach using ANOVA.
Results (300+ words): Summarize the findings with plots and tables, focusing on the statistical analysis results from the ANOVA. Highlight any significant or non-significant differences in maternal language input across gender categories, providing the necessary statistical values (e.g., F-statistic, p-values) to support the conclusions.
Discussion (400+ words): Reflect on the implications of the findings, considering how they contribute to the understanding of gender socialization through maternal language input. Discuss the limitations of the study and propose directions for future research. This section will also include reflections on what the data reveals and how it aligns or contrasts with existing literature.

3. Elements of Code in Text
Example: “Here there is a significant/non-significant difference in the male-biased and female-biased nouns of maternal child-directed language input between the 2 gender categories of children
	<!-- •	$F$() = `r round(summary(anova_mnoun_gender)[[1]]$F[1],3)` -->
	<!-- •	$p$ = `r round(summary(anova_fnoun_gender)[[1]]$P[1],3)`.” -->

4. Personal Goals for the Final Report
By the end of this project, my goal is to have gained proficiency in R, equipping with the skills to conduct comprehensive psychological research. I hope to develop skills in data cleaning, coding, and visualization techniques, and apply them to my MA thesis and future research endeavors

# Assessment

The lists of expectations in each category are to help you understand the kinds of things I'm looking for as I grade. These **do not** map onto point values. A checked box indicates the expectation was met or exceeded. (This also helps me spot patterns across students to identify ways I can improve the syllabus and lectures for future students.)

Ratings indicate overall success for each category and loosely map onto points. Starting from 20 points, no points are lost for the highest rating, -3 for the lowest, and somewhere in between for the middle ratings. Points lost in that range are dependent on how many issues there are, how much they matter, whether it's technicality vs problem of consequence, whether it's the same core issue that lost you points in a different section, whether exceeding expectations elsewhere compensate for a small issue, whether it's something we talked about in your report plan meeting, etc. 

Additional comments are included below the ratings as needed. Final project and class grades are included at the end of the document.

**WARNING: Grades for this assignment are going to be lower than you expect!** Don't freak out. I use "specs-based grading", which works very differently from the letter-grade-to-percentage conversion you are probably used to. It's more like Harry Potter OWLs -- 19/20 is outstanding, 16-18 exceeds expectations (not a C!), 13-15 meets expectations (not an F!), etc. You're not down to T(roll) until you're in the negatives. Remember this is only 20% of your final grade!

## .Rmd/PDF match

**Expectations:**

- [x] PDF submitted to Canvas is identical to the PDF created when I knit your .Rmd
- [ ] Knitting does not produce any errors or problematic warnings

**Rating:**

- [ ] Perfect match
- [ ] At least one minor problem
- [x] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive error(s), missing PDF, or significant problems

Document does not knit successfully as-is due to an absolute path (line 77). Changing this to a relative path results in successfully and identical document.

## Data read-in, prep, wrangling

**Expectations:**

- [ ] Data preparation and wrangling code present (may separate files)
- [ ] Intermediate datasets (if used) are functional and read in successfully
- [x] Raw or intermediate data read into .Rmd code chunk
- [ ] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [ ] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [x] Prohibitive errors or significant problems

I cannot find any data wrangling or preparation code in your repo. Your intermediate dataset does work (though I had to change the path to relative) but there's nothing that shows how you created that data.

## Figures, tables, analyses

### Figures

**Expectations:**

- [x] At least 2 plots are produced in .Rmd chunks (not imported images)
- [x] Figures are different kinds of plots 
- [x] Figures follow report plan (may have inconsequential deviations)
- [ ] Figures are publication-quality
- [x] Figures are sensibly captioned with `fig.cap` chunk option
- [x] Figures are informative and interpretable
- [ ] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [ ] No noteworthy issues 
- [x] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Great plots overall, but you can improve the bar plot (which is a bar plot, btw, not a histogram). The "free" y-axes make it difficult to interpret a comparison across these three facets, which is made even more difficult by the fact that the first 2 facets are words and the third is utterances. Consider making this 2 different plots (for words and utterances). I'd also suggest potentially using utts as a kind of "control" by comparing nouns-per-utterance, either by child or averaged overall, so that the disproportionately high number of utterances to females doesn't cause misleading interpretations of count comparisons. This would let the plot respresent your "proportional analysis."

Another minor point -- rename/relevel your factors to make them publication-ready. e.g., instead of "female_biased_nouns" I should see "Female Biased Nouns".

### Table

**Expectations:** 

If you included more than the one required table, only one needs to meet expectations.

- [x] At least 1 table is produced in .Rmd chunk
- [x] Table follows report plan (may have inconsequential deviations)
- [ ] Table is publication-quality
- [x] Table is sensibly captioned within the function (e.g., the kable caption argument)
- [x] Table is informative and interpretable
- [ ] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Nice! Very minor suggestion -- same as figure comment above -- relevel/refactor to make the column headers publication ready (e.g., "Name.of.child" to "Name" and "Female.biased.nouns" to "Female bias nouns")

### Analysis

**Expectations:**

If you included more than the one required analysis (or other requirements agreed on in the report plan), only one needs to meet expectations.

- [x] At least 1 statistical analysis is executed in .Rmd chunk (or sourced code if appropriate)
- [x] Analysis follows report plan (may have inconsequential deviations)
- [x] Analysis is executed correctly
- [x] Analysis is appropriate (not necessarily ideal) for data type(s) and research questions
- [x] Analysis is referenced and interpreted in narrative text
- [ ] All code in .R files and .Rmd code chunks is sufficiently commented and comprehensible
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Be sure that any model output you want to include in the final paper is presented in an APA-formatted table. output on pages 8/9 displays as raw output.

## Manuscript

### Narrative text

**Expectations:**

- [x] Narrative text includes 1500+ words distributed across 4 sections
- [x] Sufficient literature review (per report plan)
- [x] Sufficient methods section (per report plan)
- [x] Sufficient results section (per report plan)
- [x] Sufficient discussion (per report plan)
- [x] Narrative provides sufficient context and interpretation for all figures, tables, and analyses
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

*No additional comments*

### Markdown

**Expectations:**

- [x] Figures and tables are successfully referenced with markdown syntax
- [x] At least 2 in-text code references
- [x] At least 1 in-text code reference includes in-text function
- [x] R Markdown is used effectively to follow APA format (e.g., headings, emphasized text)
- [x] YAML header is functional and complete
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [x] No noteworthy issues 
- [ ] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

I see you used additional YAML markup to make your table formatting work! Nice!! Gonna steal that from you...

### BibTeX

**Expectations:**

- [x] At least 10 in-text citations using BibTeX reference syntax
- [x] In-text citations are rendered without errors
- [x] In-text citations have no obvious problems (e.g., incorrect special characters)
- [ ] R and R packages are cited in-text using `cite_r()`
- [x] References page renders without errors
- [x] References page is APA formatted and free of obvious problems
- [x] Additional expectations set in the report plan (if any) are met

**Rating:**

- [ ] No noteworthy issues 
- [x] At least one minor problem
- [ ] At least one major problem and/or multiple minor problems
- [ ] Multiple major problems
- [ ] Prohibitive errors or significant problems

Missing R and R package citations

## GitHub

These expectations will not have an impact on your grade unless there are egregious issues, but I include them to give you feedback on what you can do if you use this workflow going forward.

**Expectations:**

- [x] GitHub repo and contained files are sensibly and informatively named
- [x] GitHub repo is well-structured and tidy
- [x] GitHub README.md file is informative
- [x] Commit messages are informative
- [x] Style is (relatively) consistent
- [ ] Comments are frequent and informative
- [x] Code chunks have informative names, follow 1-chunk-1-thing rule, and are distributed throughout the text

*No additional comments*

## Overall

Excellent work, Katia! Although I have to take off points for some missing elements, I think this came together beautifully.

# Grade

- **Final report grade:** 15
- **Class participation grade:** 20
- **Weekly assignments:** 60
- **TOTAL Final course grade:** 95 (A)
